### ISSUE TITLE
No acepta imágenes importadas desde React

### ISSUE THREAD

**Issue by Israel-Laguan** [Katsu08/resizeandsave#3]
Se intento utilizar imágenes importadas y no se pudo, ayuda

**Comment by heliomar-pena** [comment]
@Israel-Laguan Solucionándose en el #4 

Ahora puedes usar la función processFile() para convertir una imagen importada (que normalmente viene codificada en base64 o en forma de ruta (/static/img/example.813a5b.png)) en un File Object de Javascript.

Con esto podrás subir las imágenes que importes, solo tienes que, antes, usar la función processFile para que la imagen esté preparada para ser usada por la librería.

[Documentación](https://github.com/Katsu08/resizeandsave#how-to-use)

**Comment by heliomar-pena** [comment]
@Israel-Laguan Ya ha sido solucionado y fue actualizada la rama principal. Gracias por informar del error
